"""reports add user_id

Revision ID: 09271c9f26c7
Revises: cb84c2c74580
Create Date: 2025-07-02 22:36:58.608585

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "09271c9f26c7"
down_revision: Union[str, None] = "cb84c2c74580"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reports", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "reports", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "reports", type_="foreignkey")
    op.drop_column("reports", "user_id")
    # ### end Alembic commands ###
