"""update regions and users

Revision ID: 14b2cd999129
Revises: 19ef1b31e8ef
Create Date: 2025-07-14 14:32:27.025398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14b2cd999129'
down_revision: Union[str, None] = '19ef1b31e8ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('admin_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('regions_ceo_id_fkey'), 'regions', type_='foreignkey')
    op.create_foreign_key(None, 'regions', 'users', ['admin_id'], ['id'], ondelete='SET NULL')
    op.drop_column('regions', 'ceo_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('ceo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'regions', type_='foreignkey')
    op.create_foreign_key(op.f('regions_ceo_id_fkey'), 'regions', 'users', ['ceo_id'], ['id'], ondelete='SET NULL')
    op.drop_column('regions', 'admin_id')
    # ### end Alembic commands ###
