"""update users model

Revision ID: 19ef1b31e8ef
Revises: ab30f191618e
Create Date: 2025-07-12 22:15:18.238065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ef1b31e8ef'
down_revision: Union[str, None] = 'ab30f191618e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_region_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'region_id')
    op.drop_column('users', 'is_region_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_region_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_region_id_fkey'), 'users', 'regions', ['region_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
