"""update model users

Revision ID: 1c49adff23a4
Revises: 2c7dfe95f09d
Create Date: 2025-07-14 14:46:48.503142

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c49adff23a4"
down_revision: Union[str, None] = "2c7dfe95f09d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("regions_admin_id_fkey"), "regions", type_="foreignkey"
    )
    op.drop_column("regions", "admin_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "regions",
        sa.Column(
            "admin_id", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.create_foreign_key(
        op.f("regions_admin_id_fkey"),
        "regions",
        "users",
        ["admin_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
