"""create reports

Revision ID: 28ac51033090
Revises: c35d3e0b2eb0
Create Date: 2025-07-02 11:47:52.259866

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "28ac51033090"
down_revision: Union[str, None] = "c35d3e0b2eb0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("point_id", sa.Integer(), nullable=True),
        sa.Column("img", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["point_id"], ["points.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("created_at", "point_id", name="unique_report_in_a_day"),
    )
    op.drop_column("points", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "points", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_table("reports")
    # ### end Alembic commands ###
