"""updateusers

Revision ID: 2c7dfe95f09d
Revises: 14b2cd999129
Create Date: 2025-07-14 14:39:07.461168

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c7dfe95f09d"
down_revision: Union[str, None] = "14b2cd999129"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("region_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "users", "regions", ["region_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "region_id")
    # ### end Alembic commands ###
