"""new init

Revision ID: 4b49a1089f50
Revises:
Create Date: 2025-07-14 20:23:40.902796

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from app.offices.constants import WORKING_SCHEDULE

# revision identifiers, used by Alembic.
revision: str = "4b49a1089f50"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "offices",
        sa.Column("addres", sa.String(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=True),
        sa.Column(
            "working_schedule",
            sqlalchemy_utils.types.choice.ChoiceType(WORKING_SCHEDULE),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_id"], ["regions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("telegram_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("ban", sa.BOOLEAN(), nullable=True),
        sa.Column("office_id", sa.Integer(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["office_id"],
            ["offices.id"],
        ),
        sa.ForeignKeyConstraint(
            ["region_id"], ["regions.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone_number"),
        sa.UniqueConstraint("telegram_id"),
        sa.UniqueConstraint(
            "telegram_id", "phone_number", name="unique_phone_number_tg_id"
        ),
    )
    op.create_table(
        "reports",
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at_date", sa.Date(), nullable=False),
        sa.Column("office_id", sa.Integer(), nullable=True),
        sa.Column("img", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["office_id"], ["offices.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "created_at_date", "office_id", name="unique_report_in_a_day"
        ),
    )
    op.create_table(
        "workdays",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("day", sa.Date(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "day", name="unique_user_work_day"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("workdays")
    op.drop_table("reports")
    op.drop_table("users")
    op.drop_table("offices")
    op.drop_table("regions")
    # ### end Alembic commands ###
