"""regions users relationship

Revision ID: 8c8b1f8007f5
Revises: 09271c9f26c7
Create Date: 2025-07-03 10:33:01.621390

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8c8b1f8007f5"
down_revision: Union[str, None] = "09271c9f26c7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("reports", "user_id", existing_type=sa.INTEGER(), nullable=False)
    op.add_column("users", sa.Column("region_id", sa.Integer(), nullable=True))
    op.create_foreign_key(
        None, "users", "regions", ["region_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "region_id")
    op.alter_column("reports", "user_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
