"""points-regions-models

Revision ID: 90ac23f24b8d
Revises: ab15d64fd6e3
Create Date: 2025-06-29 17:22:09.524254

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from app.points.constants import WORKING_SCHEDULE
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "90ac23f24b8d"
down_revision: Union[str, None] = "ab15d64fd6e3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "regions",
        sa.Column("ceo_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["ceo_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "points",
        sa.Column("addres", sa.String(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=True),
        sa.Column(
            "working_schedule",
            sqlalchemy_utils.types.choice.ChoiceType(WORKING_SCHEDULE),
            nullable=True,
        ),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["region_id"], ["regions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("users", sa.Column("first_name", sa.String(), nullable=False))
    op.add_column("users", sa.Column("last_name", sa.String(), nullable=True))
    op.alter_column(
        "workdays",
        "user_id",
        existing_type=sa.BIGINT(),
        type_=sa.Integer(),
        existing_nullable=False,
    )
    op.create_foreign_key(
        None,
        "workdays",
        "users",
        ["user_id"],
        ["telegram_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workdays", type_="foreignkey")
    op.alter_column(
        "workdays",
        "user_id",
        existing_type=sa.Integer(),
        type_=sa.BIGINT(),
        existing_nullable=False,
    )
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    op.drop_table("points")
    op.drop_table("regions")
    # ### end Alembic commands ###
