"""point model rename

Revision ID: ab30f191618e
Revises: 527b4a7fdf67
Create Date: 2025-07-06 17:04:12.861055

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab30f191618e"
down_revision: Union[str, None] = "527b4a7fdf67"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("reports", sa.Column("office_id", sa.Integer(), nullable=True))
    op.drop_constraint(op.f("unique_report_in_a_day"), "reports", type_="unique")
    op.create_unique_constraint(
        "unique_report_in_a_day", "reports", ["created_at_date", "office_id"]
    )
    op.drop_constraint(op.f("reports_point_id_fkey"), "reports", type_="foreignkey")
    op.create_foreign_key(
        None, "reports", "offices", ["office_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("reports", "point_id")
    op.add_column("users", sa.Column("office_id", sa.Integer(), nullable=False))
    op.drop_constraint(op.f("users_point_id_fkey"), "users", type_="foreignkey")
    op.create_foreign_key(None, "users", "offices", ["office_id"], ["id"])
    op.drop_column("users", "point_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("point_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("users_point_id_fkey"), "users", "offices", ["point_id"], ["id"]
    )
    op.drop_column("users", "office_id")
    op.add_column(
        "reports",
        sa.Column("point_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "reports", type_="foreignkey")
    op.create_foreign_key(
        op.f("reports_point_id_fkey"),
        "reports",
        "offices",
        ["point_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_constraint("unique_report_in_a_day", "reports", type_="unique")
    op.create_unique_constraint(
        op.f("unique_report_in_a_day"),
        "reports",
        ["created_at_date", "point_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("reports", "office_id")
    # ### end Alembic commands ###
