"""update reports model

Revision ID: b3db2b9bad05
Revises: 28ac51033090
Create Date: 2025-07-02 11:58:04.812158

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b3db2b9bad05"
down_revision: Union[str, None] = "28ac51033090"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "reports", sa.Column("created_at_date", sa.DateTime(), nullable=False)
    )
    op.drop_constraint(op.f("unique_report_in_a_day"), "reports", type_="unique")
    op.create_unique_constraint(
        "unique_report_in_a_day", "reports", ["created_at_date", "point_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_report_in_a_day", "reports", type_="unique")
    op.create_unique_constraint(
        op.f("unique_report_in_a_day"),
        "reports",
        ["created_at", "point_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("reports", "created_at_date")
    # ### end Alembic commands ###
