"""update workdsays user_id field

Revision ID: ee760463f291
Revises: ca740ea08d9a
Create Date: 2025-07-01 18:54:02.351030

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ee760463f291"
down_revision: Union[str, None] = "ca740ea08d9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("workdays_user_id_fkey"), "workdays", type_="foreignkey")
    op.create_foreign_key(
        None, "workdays", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workdays", type_="foreignkey")
    op.create_foreign_key(
        op.f("workdays_user_id_fkey"),
        "workdays",
        "users",
        ["user_id"],
        ["telegram_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
