services:
  postgres_db:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
  main_bot:
    build:
      context: .
    env_file:
      - main.env
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
volumes:
  postgres_data: