services:
  main_bot:
    image: eliaswide/manager_tg_bot
    env_file:
      - main.env
    restart: on-failure
    ports:
      - "8000:8000"
    depends_on:
      - postgres_main

  postgres_main:
    image: postgres:latest
    env_file:
      - db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: